-- ORACLE
CREATE TABLE USER_TBL (
    UUID NUMERIC(38) NOT NULL,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    TENANT_ID VARCHAR2(50),
    CONSTRAINT UUID_PK PRIMARY KEY (UUID)
);

CREATE SEQUENCE UUID_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE TRIGGER UUID_SEQ_TR
 BEFORE INSERT ON USER_TBL FOR EACH ROW
 WHEN (NEW.UUID IS NULL)
BEGIN
 SELECT UUID_SEQ.NEXTVAL INTO :NEW.UUID FROM DUAL;
END;
/

-- MYSQL
CREATE TABLE USER_TBL (
    UUID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    TENANT_ID VARCHAR(50),
    PRIMARY KEY UUID_PK (UUID)
);
